title: Meixia LIN
baseurl: "/homepage"
url: "linmeixia.github.io"
google_analytics: 

author:
  name: Meixia LIN (林媚霞)
  desc: Nice to meet you.
  email: linmx@nus.edu.sg  or  meixia.lin.math@gmail.com
  selfie: assets/img/lmx.jpg

social:
  email: true
  github: linmeixia
  default_txt: "Follow On"

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate

permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
